### PR TITLE
Use the Trustpilot Widget on Xero with a minor refactor to make that sensical.

### PR DESCRIPTION
**Pull request by kylorhall**
See the [Vimaly Story](https://vimaly.com/#j8mqm/t/www_Trustpilot_widget_on_Xero_page/T7dOxiKiqzVEhRuIg).

I believe all we need is the tag `widget-xero`, whereas the main one has `widget-general-nz`, `widget-general-global` (etc).

I think this works, I didn't run it locally.

### CODE REVIEW

**Review by irwalker — COMMENTED** [review]
Looks like some CI issues?

**Comment by kylorhall** [comment]
> Looks like some CI issues?

Eh, what?  Bundler in CI going awry…?  😨 
> bundler: failed to load command: middleman (/opt/hostedtoolcache/Ruby/2.6.6/x64/bin/middleman)
> Message: Response size too big. Maximum allowed response size: 7340032B.

**Comment by kylorhall** [comment]
Nevermind, someone broke the Drafts.  Slack#static-site-builds

**Comment by kylorhall** [comment]
@irwalker Can you re-review next week?  It should be fully green…thanks for pointing out the CI failure, that only consumed all of my day.

**Review by irwalker — APPROVED** [review]
Change looks good and looks OK on staging

**Pull request merged**
