### PR TITLE
Adding Multi-Currency Valuation Report to pricing page

### PR DESCRIPTION
**Pull request by maisiembleton**
See the vimaly ticket [here](https://vimaly.com/#j8mqm/t/www_investapp_Add_Multi-Currency_Valuation_Report.../wMG4HbpCRWhf6a9sT)

### CODE REVIEW

**Review by kylorhall — APPROVED** [review]
Pretty sure this LGTM 👍 

Not 100% sure if it should be at the bottom…or where…but I don't think it was described in the story, so it's probably fine as-is.

Pop it into staging (merge into the _develop_ branch and it will be at staging-www.sharesight.com), then submit it for QA as long as that's good.

**Review by Billyhaine — APPROVED** [review]
LGTM however id note the ticket was to do `www` _and_ investapp. I'd suggest QA'ing them seperately & then merging them at the same time

**Comment by maisiembleton** [comment]
> LGTM however id note the ticket was to do `www` _and_ investapp. I'd suggest QA'ing them seperately & then merging them at the same time

Thanks for the suggestion!  I've created a child ticket to cover just the `www` to  help with the QA flow

**Comment by felixibel** [comment]
Thanks @maisiembleton 👍  💯 
I did the [investapp part (PR 8593)](https://github.com/sharesight/investapp/pull/8593)

PS. You forgot to assign yourself to the vimaly ticket ;)

**Pull request merged**
