### PR TITLE
Update Ruby from 2.4.2 to 2.6.5

### PR DESCRIPTION
**Pull request by alto**

### CODE REVIEW

**Comment by kylorhall** [comment]
@alto Just looking at [www] PRs.  I think this can merge into `develop` and then `master`.

I have been running it locally on both 2.6.5 and 2.7.1, no noticed issues..  Only unchecked part is the deploy step.

I'd even go one step further and upgrade to latest `2.7.1`?

**Comment by alto** [comment]
@kylorhall I would go with Ruby 2.6.5 for now, as this is the version we are using for _investapp_ etc too. Maybe 2.7 in a follow-up PR.

**Review by kylorhall — APPROVED** [review]
:+1:

I run on `2.6.5` locally, but have ran it on `2.7.x`.  Regardless, parity with Investapp makes the most sense.

**Comment by kylorhall** [comment]
Merged onto _staging_.

**Comment by kylorhall** [comment]
This successfully deployed onto our staging environment and looking fine.

**Pull request merged**
