### PR TITLE
Use `bundler-audit` directly rather than a mis-named package.

### PR DESCRIPTION
**Pull request by kylorhall**
- Use `bundler-audit` directly rather than a mis-named package.
 - Make the gemfile use consistent quoting.
 - Bump `bundler-audit` to `0.7.0.1` (taken from https://github.com/sharesight/help.sharesight.com/pull/75)

### CODE REVIEW

**Comment by kylorhall** [comment]
Failing CI due to some FAQ stuff in [this story](https://vimaly.com/#j8mqm/t/www_Replace_existing_FAQ_page_with_Contentful_Land.../UrVeAiv9ws1VZHVrr).  Passing CI in the develop branch.

**Review by alto — APPROVED** [review]
I would rather see #205  getting merged, but it's a step 👍

**Comment by kylorhall** [comment]
@alto I think I'll just merge this as-is once it's green and pushed into _develop_, but also think we can progress with #205.

**Comment by alto** [comment]
Yep, merge this one 👍

**Pull request merged**
