### PR TITLE
Preload fonts and make the page progressively load faster.

### PR DESCRIPTION
**Pull request by kylorhall**
[Vimaly Story](https://vimaly.com/#j8mqm/t/www_Preload_and_progressively_load_fonts_better./HvNZj0e8cyIAIagQq)

**Changes:**
 - Preload fonts as they are requested to load after `site.css` has loaded.  I did not preload all fonts, but the common ones.
 - Progressively load fonts rather than not painting (via `font-display: swap`).

### CODE REVIEW

**Review by kyle-beattie — COMMENTED** [review]
`font-display: swap;` will cause FOUT right? Are we cool with that? Is it still a big deal in 2021?

**Comment by kylorhall** [comment]
> `font-display: swap;` will cause FOUT right? Are we cool with that? Is it still a big deal in 2021?

Yeah, I'm not actually sure at all…these classic Web Design things are just lost on me after all these years.  I think it's FOIT or FOUT.  Right now, I think it's render blocking…so "Flash of White Background"?

**Comment by kylorhall** [comment]
@kyle-beattie I'm just shipping this.  I couldn't even replicate a `FO…F` very well, so I didn't even run through it much.  🤷 it's something of an improvement if nothing else.

**Comment by kyle-beattie** [comment]
Cool - no worries, pretty minor issue these days I think

**Pull request merged**
