### PR TITLE
Updating the Sharesight logo 

### PR DESCRIPTION
**Pull request by maisiembleton**
The ticket can be found [here](https://vimaly.com/#j8mqm/t/Replace_logo_across_all_middleman_pages_in_the_hea.../ltqZvv3qWxREwE0O4)

### CODE REVIEW

**Review by kylorhall — CHANGES_REQUESTED** [review]
This is probably missing favicons and a bit more, can you investigate a bit further?  The originally scoped ticket for the Investapp repo was lacking as well.

**Comment by maisiembleton** [comment]
> 

@kylorhall can do!

**Review by Billyhaine — COMMENTED** [review]
LGTM ~ but +1 to kylors "investigate more" suggestion

**Comment by maisiembleton** [comment]
Sweet - replaced the favicons with the updated versions - also found that the pro sharesight logo didn't seem to be used anywhere, so removed it. Skimmed through the images in the `img` folder and didn't see any other instances of the sharesight logo. Seeeems a bit more straightforward than the investapp swapover?

**Review by kylorhall — APPROVED** [review]
LGTM.

Was there a Gatsby variant of this too?

**Comment by maisiembleton** [comment]
> LGTM.
> 
> Was there a Gatsby variant of this too?

@kylorhall it looks like the only versions in static-www are the newer version!

**Comment by kylorhall** [comment]
> @kylorhall it looks like the only versions in static-www are the newer version!

Oh…yeah 😅

**Pull request merged**
