### PR TITLE
Enable the 301 redirects in s3 process.

### PR DESCRIPTION
**Pull request by kylorhall**
[trying for ticket](https://vimaly.com/#j8mqm/t/www_Pages_not_resolving_without_trailing_slash/9i5wdb6iYkJJ2wZKY)

### CODE REVIEW

**Comment by kylorhall** [comment]
Edit: don't do this.

**Comment by kylorhall** [comment]
So we need run `S3RedirectsHelper::make_s3_redirects`, but the `after_build` just simply doesn't work—it's 100% broken.

This has to be ran manually?  Not sure how.

**Comment by kylorhall** [comment]
@michael-sands I'm not quite sure what to do on this, but if you want to take a look, my takeaways:
1. It appears that s3_sync runs no matter what, regardless of whether or not we're deploying..?  I'm confused by this..  This build: https://travis-ci.org/sharesight/www.sharesight.com/builds/527127342 broke the _production_ website because it was, in a PR build, deploying to s3?  😱 I do not understand what the `build` vs `deploy` stages even do now..
2. Never set `after_build = true`, apparently this just *never* will work and outright breaks everything.  Not sure why it's a setting....plugin creator confirms it doesn't work.  💯 
3. We need to run this method: `helpers/s3_redirects_helper.rb::make_s3_redirects` — I don't know how to run this file in isolation...especially since it needs some configuration.

Ideally, I think we'd run `make_s3_redirects` in the `bin/travis/deploy.sh` file after it's been deployed, but I don't know how 🤷‍♂..

**Comment by michael-sands** [comment]
@kylorhall I will see what I can figure out in the morning.

**Comment by kylorhall** [comment]
@michael-sands Actually, I think @alto and I resolved this this morning.

See two latest commits.  There were a few minor changes to the script, namely migrating it out of the entire process so it isn't ran accidentally sort of thing.

I believe if we merge this into develop and ran with a FORCE_SYNC commit, this will work...  However, it will take like 20+ minutes...

Locally, you could try:
```sh
$ bundle && yarn
$ APP_ENV=staging bundle exec middleman build
$ APP_ENV=staging bundle exec ruby tasks/build_s3_redirects.rb
```

Ideally, if this works, we'd have it on _master_ before the weekend since people are already running.

Alternatively, just adding `x-amz-website-redirect-location` to the specific files in S3 might help...

Leaving for a flight around 10am, will be on/off most of the day.

**Comment by kylorhall** [comment]
Actually, just trying now.

**Pull request merged**
