### PR TITLE
Rubocop 1 18

### PR DESCRIPTION
**Pull request by CitationNerded**

### CODE REVIEW

**Comment by CitationNerded** [comment]
Okay this is probably more hassle than its worth. what do people think in principal @sharesight/backend ? should we spend some time to introduce linting into this repo or is it too far gone?

**Comment by alto** [comment]
@CitationNerded I don't think it's worth putting the effort in. This repo might die soon, as it gets replaced by the [Gatsby project](https://github.com/sharesight/static-www).

**Comment by felixibel** [comment]
Ye, exactly. Gatsby is the future; Middleman has dieded swo hard :trollface:

**Comment by CitationNerded** [comment]
This isn't worth the effort as discussed :)

**Pull request closed without merging**
